//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscreteMathCourseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopicContent()
        {
            this.UserTopicContents = new HashSet<UserTopicContent>();
        }
    
        public int Id { get; set; }
        public int TopicId { get; set; }
        public string TopicTitle { get; set; }
        public string TopicLink { get; set; }
        public int IndexNumber { get; set; }
    
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTopicContent> UserTopicContents { get; set; }
    }
}
