//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscreteMathCourseApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTopicContent
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public int TopicContentId { get; set; }
        public bool IsStudied { get; set; }
    
        public virtual TopicContent TopicContent { get; set; }
        public virtual User User { get; set; }
    }
}
